### ISSUE TITLE
how to "Drop me a Line"?

### ISSUE THREAD

**Issue by jixuan1989** [JorenSix/TarsosLSH#1]
I use this lib in my homework for Image and Audio Search ,Thank U very much.
“Drop me a line if you use TarsosLSH in your project. Always nice to hear how this software is used.” but I do not know how to do it .I have to write it here.
By the way, I think as a  lib, some class lost some method .
For example:
 I add  "public Vector(String key,double[] double){}" to create a vector immediately(this is very important , I think)
I add some method to get dataset from memory instead of disk file, like:
“public LSH createIndex(double radius,String hashFamilyType,int numberOfHashes,int numberOfHashTables,int numberOfNeighbours,List<Vector> dataset){}” for more convenient.

**Comment by JorenSix** [comment]
I have added my email to the readme
