### ISSUE TITLE
EuclideanDistance doesn't seem to work correctly

### ISSUE THREAD

**Issue by thobson** [JorenSix/TarsosLSH#3]
The command line runner help is incorrect regarding EuclideanDistance:  
```
if(radius == 0 && hashFamilyType.equalsIgnoreCase("l1")){
  measure = new CityBlockDistance(); 
  ...
} else if (radius == 0 && hashFamilyType.equalsIgnoreCase("l2")){
  measure = new CityBlockDistance();
  ...
}
```
CityBlockDistance is used for both L1 and L2

**Comment by JorenSix** [comment]
Hi, 

Thanks for the bug report, I have committed a fix (c759f2be7feea207a01cd4b2ffe4a5f088ff7585).
